export enum CartActions {
  ADD_ITEM_TO_CART = 'ADD_TO_CART',
  REMOVE_ITEM_FROM_CART = 'REMOVE_FROM_CART',
  INCREASE_QUANTITY = 'INCREASE_QUANTITY',
  DECREASE_QUANTITY = 'DECREASE_QUANTITY',
  CLEAR_CART = 'CLEAR_CART',
}
